---
title: "example"
author: "Elena Bagnera"
date: "11/13/2021"
output: html_document
---

```{r include = FALSE}
def.chunk.hook <- knitr::knit_hooks$get("chunk")
knitr::opts_chunk$set(cache = FALSE)
knitr::knit_hooks$set(
  chunk = function(x, options) {
    x <- def.chunk.hook(x, options)
    ifelse(options$size != "normalsize", paste0("\n \\", options$size, "\n\n", x, "\n\n \\normalsize"), x)
  }
)
# knitr::knit_hooks$set(inline = function(x) {
#   prettyNum(round(x, 2), big.mark = ",")
# })
options(scipen=999)
```


\begin{center}
\Huge{PPOL 670 | Final Project}

\Huge{Example}
\end{center}

\vspace{0.1in}

## Setup
```{r setup, message=FALSE}
library(tidyverse)
source("times.R")
source("io.R")
source("manipulate_data.R")
```


[Direct link to datasets](https://s3.amazonaws.com/capitalbikeshare-data/)

```{r get_data, cache=FALSE, warning=FALSE, message=FALSE}

# Read all the data
cbs_data <- read_files('data/')

# Read one month for testing
# cbs_data <- read_csv("data/202107-capitalbikeshare-tripdata.csv")

data <- sep_departures_from_arrivals(cbs_data) %>% 
  filter(!is.na(station)) # Remove electric bikes not going to / from a station

filtered_data <- filter_by_distance(data, from_station = 'lincoln_memorial', distance_m = 800)

hour_data <- get_station_hourly(filtered_data) %>% 
  get_historic_weather()

# Stop here to work with current data. This is all you need! The below code sets up the data for time predictions at a given station and adds other predictors
```


```{r ridership, cache=FALSE, warning=FALSE, message=FALSE}
# This lags all the data that is currently in hour_data, so weather is also 14 day
# lagged
lagged_data <- setup_for_time_prediction(hour_data, station_name = "lincoln_memorial")
glimpse(lagged_data)

# Recommended next steps before modeling
lagged_data %>% 
  filter(!is.na(departures) & !is.na(arrivals))
```


```{r test_ridership, warning=FALSE, message=FALSE}
# Just testing one data point to make sure ridership is corret.
#  Should test this is working as intended.
# ridership_data's lincoln_memorial column should match the hour_data's 
#  lincoln memorial from 14 days prior.
# Ridership_data's ridership should match hour_data's lincoln memorial from the same date.
hour_data %>% 
  select(lincoln_memorial_departures, year, month, day, hour) %>% 
  filter(year == 2021, month == "Jul", day == 3, hour == 12)
  
hour_data %>% 
  select(lincoln_memorial_departures, year, month, day, hour) %>% 
  filter(year == 2021, month == "Jul", day == 17, hour == 12)
  
ridership_data %>% 
  select(departures, lincoln_memorial_departures, year, month, day, hour) %>% 
  filter(year == 2021, month == "Jul", day == 17, hour == 12)

```
